CC = gcc
CFLAGS = -g -Wall
SERVEROBJECTS = TCPserver.c
CLIENTOBJECTS = TCPclient.c TCPmain.c
SERVERNAME = TCPserver
CLIENTNAME = TCPclient
TODELETE = $(SERVERNAME) $(CLIENTNAME) *.o
LIBS = -pthread

all: $(SERVERNAME) $(CLIENTNAME)

$(SERVERNAME): $(SERVEROBJECTS)
	$(CC) $(CFLAGS) $(SERVEROBJECTS) -o $(SERVERNAME) $(LIBS)

$(CLIENTNAME): $(CLIENTOBJECTS)
	$(CC) $(CFLAGS) $(CLIENTOBJECTS) -o $(CLIENTNAME)

.PHONY: clean
clean:
	rm -f $(TODELETE)